### ISSUE TITLE
[1.3.13] No internet connection not handled gracefully

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/cli#208]
```
{ FetchError: request to https://api.graph.cool/system failed, reason: getaddrinfo ENOTFOUND api.graph.cool api.graph.cool:443
    at ClientRequest.<anonymous> (C:\Users\Brandwijkk\AppData\Roaming\npm\node_modules\graphcool\node_modules\node-fetch\index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:399:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:62:8)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
  name: 'FetchError',
  message: 'request to https://api.graph.cool/system failed, reason: getaddrinfo ENOTFOUND api.graph.cool api.graph.cool:443',
  type: 'system',
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND' }
 !    Received invalid token. Please try graphcool auth again to get a valid token.
```

**Comment by kbrandwijk** [comment]
Also, I have to re-authenticate, so apparently the loss of connection also cleared my token.

**Comment by marktani** [comment]
The fundamental problem is described here, including our approach to tackle it: https://github.com/graphcool/graphcool/issues/595.
